#!/bin/bash
# Download all sources for $1 file in sequence

pop(){
	queue="${1}"
	lines=$(wc -l ${queue} | awk '{print $1}')
	tmp=$(mktemp)

	if (( $lines > 0 ))
	then
		sed -i '1d' ${queue}
	fi
}

dst="$(realpath "${1:-queue}")"
if [[ -z $dst ]]; then
	echo no queue file
	exit 1
fi
cat "${dst}" | while read line; do
	youtube-dl "${line}" && pop "${dst}"
done

unset dst
exit 0
